### PR TITLE
[ENHANCEMENT] Add `is` operator

### PR DESCRIPTION
**Pull request by gamerbross**
Just adds support to `is` operator.

It requires having `Std` in variables.

(PD: when is a new release gonna come out?)

### CODE REVIEW

**Comment by ncannasse** [comment]
Im not a big fan on relying on Std being an accessible variable, I think this would work better as a EBinop "is"

**Comment by gamerbross** [comment]
done! it no longer depends on having Std in the script variables, i changed it to be an operator

**Comment by ncannasse** [comment]
Uhm I'm not sure about the parser part. Maybe we should match expr EIdent("is") expr2 in the parsing of expressions and not in the lexer ?

**Comment by gamerbross** [comment]
i think its better now

**Comment by ncannasse** [comment]
Thanks!

**Pull request merged**
