### PR TITLE
Add filename / line number error reporting with -D hscriptPos

### PR DESCRIPTION
**Pull request by tcoxon**
This fixes the (currently broken) build with -D hscriptPos and adds some new functionality to report errors with the filename and line number.

The "filename" is just an arbitrary string that can optionally be passed into Parser.parseString / Parser.parse. It's preserved in the Expr nodes until runtime, and through byte format conversions. When the interpreter or parser throws an error, the filename and line number information is included.

As an added bonus, the hscript `trace` function now also uses this information to print the location of the hscript trace call. :)

### CODE REVIEW

**Comment by ncannasse** [comment]
The check for `e2.e == null` in TIf seems wrong to me
Also, please define a single inline function to access the expr enum in Interp depending if it's hscriptPos or not

**Comment by tcoxon** [comment]
> The check for e2.e == null in TIf seems wrong to me

What in particular seems wrong about it? When I tested with an if-expression with no else-clause, I found that e2 was a non-null Expr, while e2.e (an ExprDef) was null. Perhaps e2 is supposed to be null, and the hscriptPos parser is wrong?

**Comment by ncannasse** [comment]
Yes I think in that case e2 should be null, not with a .e being null

**Comment by tcoxon** [comment]
Please check again.

> The check for e2.e == null in TIf seems wrong to me

Parser no longer wraps null ExprDefs into Exprs.

> Also, please define a single inline function to access the expr enum in Interp depending if it's hscriptPos or not

Turns out there already was one called edef! I've used that instead of #ifs now.

There appears to be a test failure when the library is built with hscriptPos to do with the Bytes serialization. I think that is an issue that already existed before though?

**Pull request merged**
