### PR TITLE
added run script

### PR DESCRIPTION
**Pull request by sebthom**
This patch adds a run script for hscript that allows you to do things like this:

	C:> haxelib run hscript --help
	hscript v2.0.5
	Haxe Script is a scripting engine for a subset of the Haxe language

	usage: haxelib run hscript SCRIPT
	   or: haxelib run hscript -f SCRIPTPATH
	   or: haxelib run hscript --file SCRIPTPATH

	examples:
	   C:\>haxelib run hscript var x = 4; 1 + 2 * x
	   9

	   C:\>haxelib run hscript "5 | 6"
	   7

	   C:\>haxelib run hscript for(i in 0...5) Sys.stdout().writeString(i + ', '); 'done'
	   0, 1, 2, 3, 4, done

	   C:\>haxelib run hscript Host.localhost()
	   mycomputer

	   C:\>for /f %i in ('haxelib run hscript "new Host('')"') do @set MY_IP=%i
	   C:\>echo %MY_IP%
	   192.168.248.1

### CODE REVIEW

**Comment by ncannasse** [comment]
Nice, but could you expose classes with their packages ?
We would use `new sys.net.Host` instead of `new Host` for instance.

**Comment by deathbeam** [comment]
Just my two cents. Please, remove that C:\> from that `examples:` :D

**Comment by sebthom** [comment]
Better?

**Comment by ncannasse** [comment]
I don't this this will work, you need to set variables.set("sys", { FileSystem : FileSystem, ... }) etc.

**Comment by sebthom** [comment]
Ok, should work now. :-)

**Comment by ncannasse** [comment]
Thanks!

**Pull request merged**
